name: ${project.name}
main: ${main.class}
version: ${project.version}
database: true
description: >
             ${project.name} is a death/frag plugin for bukkit.

commands:
  frags:
    description: Returns information about how many entites a player killed.
